name: crDroid_build_kernel

env:
  KERNEL_SOURCE:  'https://github.com/raystef66/android_kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH:  '12.1-cepheus'
  KERNEL_CONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'crDroid-cepheus'
  ARCH:  'arm64'
  KERNEL_FILE:  'Image.gz-dtb'
  
on:
  schedule:
    - cron: '0 8 * * */5'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup the evironment
        run: |
          echo "kernel source : ${{env.KERNEL_SOURCE}}"
          echo "kernel source bach : ${{env.KERNEL_SOURCE_BRANCH}}"
          echo "kernel defconfig : ${{env.KERNEL_DEFCONFIG}}"
          echo "kernel name : ${{env.KERNEL_NAME}}"
          sudo apt-get update

      - name: Download Kernel Source
        run: |
          echo "download kernel source"
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          git clone ${{env.KERNEL_SOURCE}} -b ${{env.KERNEL_SOURCE_BRANCH}} android-kernel --depth=1

      - name: Fix the Kernel Source
        run: |
          echo "delete yaml scrpit"
          rm $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts/dtc/yamltree.c
          cp $GITHUB_WORKSPACE/patch/EcrosoftXiao_kernel/scripts/dtc/* $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts/dtc
          
      - name: Startup KernelSU
        run: |
          echo "add kernelsu"
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{env.KERNEL_CONFIG}}
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{env.KERNEL_CONFIG}}
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{env.KERNEL_CONFIG}}
          
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          
      - name: Build Kernel
        run: |
          echo change build config
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          rm .git -R
          sed -i '/supported.versions.*/d' anykernel.sh
          sed -i '/do.devicecheck.*/d' anykernel.sh
          
          sed -i "s/KERNEL_NAME=.*/KERNEL_NAME=${KERNEL_NAME}-"$(date "+%Y%m%d%H%M%S")"/g" build.sh

          DATE=$(date +"%Y%m%d")
          VERSION=$(git rev-parse --short HEAD)
          KERNEL_NAME=crDroid-cepheus-"$DATE"
          
          export KERNEL_PATH=$GITHUB_WORKSPACE/kernel_workspace/android-kernel
          export ANYKERNEL_PATH=~/Anykernel3
          export CLANG_PATH=~/proton-clang
          export PATH=${CLANG_PATH}/bin:${PATH}
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export ARCH=arm64
          export SUBARCH=arm64
          
          echo "===================Setup Environment==================="
          git clone --depth=1 https://github.com/kdrag0n/proton-clang $CLANG_PATH
          git clone https://github.com/osm0sis/AnyKernel3 $ANYKERNEL_PATH
          sh -c "$(curl -sSL https://github.com/akhilnarang/scripts/raw/master/setup/android_build_env.sh/)"
          
          echo "=========================Clean========================="
          rm -rf $KERNEL_PATH/out/ *.zip
          make mrproper && git reset --hard HEAD
          
          echo "=========================Build========================="
          make O=out CC="ccache clang" CXX="ccache clang++" CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld cepheus_defconfig
          make O=out CC="ccache clang" CXX="ccache clang++" CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld 2>&1 | tee out/kernel.log

      # - name: Download kernel source
      #   run: |
      #     mkdir -p $GITHUB_WORKSPACE/kernel_workspace && cd $GITHUB_WORKSPACE/kernel_workspace
      #     git clone https://github.com/raystef66/android_kernel_xiaomi_cepheus -b 12.1-cepheus android-kernel --depth=1
      #     rm -f $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts/dtc/yamltree.c
      #     cp $GITHUB_WORKSPACE/patch/EcrosoftXiao_kernel/scripts/dtc/* $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts/dtc/
      #     sed -i '/supported.versions.*/d' $GITHUB_WORKSPACE/kernel_workspace/android-kernel/anykernel.sh
      #     sed -i '/do.devicecheck.*/d' $GITHUB_WORKSPACE/kernel_workspace/android-kernel/anykernel.sh

      # - name: Setup KernelSU
      #   run: |
      #     cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
      #     curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s
      #     echo "UPLOADNAME=-KernelSU" >> $GITHUB_ENV

      # - name: Setup Configuration for Kernel
      #   run: |
      #     cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
      #     echo "CONFIG_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
      #     echo "CONFIG_HAVE_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
      #     echo "CONFIG_KPROBE_EVENTS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
      
      # - name: do build
      #   run: |
      #     cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
      #     sudo bash build.sh
      #     # make O=out clean mrproper CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ ${KERNEL_DEFCONFIG}
      #     # make O=out CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ -j$(nproc --all)

      - name: Check a kernel output files
        run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         if [ -f android-kernel/out/arch/amr64/boot/${{ env.KERNEL_FILE }} ]; then
             echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
         else
             echo "Kernel output file is empty"
         fi

      - name: Make Anykernel3
        if: env.CHECK_FILE_IS_OK == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/osm0sis/AnyKernel3
          cp android-kernel/out/arch/arm64/boot/${{ env.KERNEL_FILE }} anykernel/
          rm -rf anykernel/anykernel.sh
          cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/anykernel.sh anykernel/
          rm -rf anykernel/.git* anykernel/README.md

      - name: Upload AnyKernel3
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
          path: kernel_workspace/anykernel/*

